export const products = [
  {
    id: 1,
    name: "Suede-BLK",
    price: 4200,
    category: "Casual",
    description: "Feather-light daily trainer with engineered mesh, micro-perf toe box, and high-rebound Pebax midsole for smooth miles.",
    image: "images/aeroflex-runner.svg",
  },
  {
    id: 2,
    name: "Wickford-BRN",
    price: 5200,
    category: "Formal",
    description: "Full-grain leather cupsole sneaker with memory-foam collar, waxed laces, and stitched outsole for all-day wear.",
    image: "images/citystride-leather.svg",
  },
  {
    id: 3,
    name: "Mandatory-BLK",
    price: 4900,
    category: "Boots",
    description: "Waterproof Gore-Tex bootie, 5mm chevron lugs, and rock plate for wet roots, rock gardens, and gravel grinds.",
    image: "images/trailcore-gtx.svg",
  },
  {
    id: 4,
    name: "Crossway-BRN",
    price: 5400,
    category: "Premium",
    description: "4-way stretch knit, wide stabilizing base, and dual-density midsole tuned for squats, jumps, and HIIT flow.",
    image: "images/studioflex-knit.svg",
  },
  {
    id: 5,
    name: "Polperro Navy",
    price: 4500,
    category: "Casual",
    description: "Retro court silhouette with suede overlays, Ortholite footbed, and rubber herringbone traction for city days.",
    image: "images/metrocourt-retro.svg",
  },
  {
    id: 6,
    name: "Lunenburg Brown",
    price: 4800,
    category: "Casual",
    description: "Race-day snap with a composite forefoot plate, nitrogen-infused foam, and decoupled heel for fast transitions.",
    image: "images/sprintvelocity.svg",
  },
  {
    id: 7,
    name: "Winsor",
    price: 5300,
    category: "Boots",
    description: "Vibram-inspired Megagrip rubber, heel brake, and midfoot cage to stay planted on slick switchbacks.",
    image: "images/terragrip-low.svg",
  },
  {
    id: 8,
    name: "Double Lace Up-Brown",
    price: 5600,
    category: "Premium",
    description: "TPU sidewalls for rope climbs, ventilated tongue, and firm heel clip to anchor heavy lifts.",
    image: "images/pulse-trainer-pro.svg",
  },
  {
    id: 9,
    name: "Oscar-BRN",
    price: 5500,
    category: "Formal",
    description: "Classic Oxford design with premium brown leather, sleek profile, and cushioned insole for elegant comfort.",
    image: "images/oscar-brn.svg",
  },
  {
    id: 10,
    name: "Lucca-BLK",
    price: 5800,
    category: "Formal",
    description: "Sophisticated black leather derby with hand-stitched detailing, timeless silhouette for any formal occasion.",
    image: "images/lucca-blk.svg",
  },
  {
    id: 11,
    name: "Galore-MRN",
    price: 5700,
    category: "Boots",
    description: "Premium maroon leather boot with rugged sole, ankle support, and vintage styling for a bold statement.",
    image: "images/galore-mrn.svg",
  },
  {
    id: 12,
    name: "Monk-BLK",
    price: 5900,
    category: "Premium",
    description: "Elegant black monk strap shoe with double buckle closure, polished leather, and refined craftsmanship.",
    image: "images/monk-blk.svg",
  },
];

export const featuredProducts = [products[0], products[5], products[2], products[4]];

export const reviews = [
  { id: 1, name: "Avery", review: "Ridiculously comfy and super light. Perfect for my daily 5k.", rating: 5, productId: 1 },
  { id: 2, name: "Jordan", review: "The leather finish looks premium and goes with everything.", rating: 4, productId: 2 },
  { id: 3, name: "Taylor", review: "Grip is excellent on wet trails. Sizing runs a half size small.", rating: 4, productId: 3 },
  { id: 4, name: "Morgan", review: "Stable for squats and lateral moves. Breathes well.", rating: 5, productId: 4 },
];
